export const LOADING = 'LOADING';
export const SET_USER = 'SETTING CURRENT USER';
export const SET_BANK_ACCOUNT = 'CREATE A NEW ACCOUNT';
export const LOADING_BANK_ACCOUNT = 'FETCHING BANK ACCOUNT';
export const SET_ERROR = 'SETTING ERROR';
export const SET_ACCOUNTS_ERROR = 'SETTING ACCOUNTS ERROR';
export const SET_TRANSACTIONS = 'SETTING TRANSACTIONS';
